<?php
/********************
 * Developed by Anukkrit Shanker
 * Time-08:27 PM
 * Date-06-02-2021
 * File-Payment.php
 * Project-gokwik-php-sdk
 * Copyrights Reserved
 * Created by PhpStorm
 *
 *
 * Working-
 *********************/


namespace Gokwik\Api;


class Payment extends Entity {
    //Payment-> verify
    function verify($attributes = null)
    {
        echo "Payment verify\n";
        return parent::verify($attributes); // TODO: Change the autogenerated stub
    }



}