<?php
/********************
 * Developed by Anukkrit Shanker
 * Time-03:58 AM
 * Date-09-02-2021
 * File-Plugin.php
 * Project-php-plugin-sdk
 * Copyrights Reserved
 * Created by PhpStorm
 *
 *
 * Working-
 *********************/


namespace Gokwik\Api;


class Plugin extends Entity
{
    function activate($url)
    {
        $data = array(
            'url' => $url,
            "status" => "activate",
        ) ;
        return parent::status_log($data); // TODO: Change the autogenerated stub
    }

    function deactivate($url){
        $data = array(
            'url' => $url,
            "status" => "deactivate",
        ) ;
        return parent::status_log($data); // TODO: Change the autogenerated stub
    }

    function uninstall($url){
        $data = array(
            'url' => $url,
            "status" => "uninstall",
        ) ;
        return parent::status_log($data); // TODO: Change the autogenerated stub
    }

    function health_check()
    {
        return parent::health_check(); // TODO: Change the autogenerated stub
    }


}